# For full config options, check the docs:
#    docs.serverless.com

service:
    name: serverless-typescript-ts-jest

# Add the serverless-webpack plugin
plugins:
    - serverless-webpack
    - serverless-offline

provider:
    name: aws
    runtime: nodejs8.10
    stage: dev
    region: us-east-1

functions:
  hello:
        handler: src/handlers/hello.HelloWorld
        description: Example endpoint
        events:
        - http:
            path: helloworld
            method: get

